
INSERT INTO
  TB_PEDIDOS_NOVAVENTA ( 
    Plataforma, Campaña, Fecha_Recepcion, Hora_Recepcion, Manifiesto, Region, Zona, Seccion, Nombre_destinatatio,
    Cedula, Numero_Boleta, Direccion, Departamento, Ciudad, Barrio, Telefono, Tipo,
    Promesa_de_Entrega, Estado_Pedido, Asignaciones, Usuario_Movil, Placas_del_Usuario_Movil, Estado_Entrega, Fecha_Entrega,
    Hora_Entrega, Nov_Entrega, Obs_Entrega, Direccion_Tercero, Nombre_Tercero, Foto1, Foto2,
    Foto3, Foto4, Foto5, Numero_Asignacion, Numero_Despacho, Fecha_Despacho, Hora_Despacho,
    Latitud, Longitud, Pedido_Inventariado, Novedad_Inventario, Observacion_Inventario, Clasificacion_por_Valor,
    Subestado, Transportador
  )
VALUES
  ? ON DUPLICATE KEY
UPDATE
  Plataforma = VALUES(Plataforma),
  Campaña = VALUES(Campaña),
  Fecha_Recepcion = VALUES(Fecha_Recepcion),
  Hora_Recepcion = VALUES(Hora_Recepcion),
  Manifiesto = VALUES(Manifiesto),
  Region = VALUES(Region),
  Nombre_destinatatio = VALUES(Nombre_destinatatio),
  Cedula = VALUES(Cedula),
  Direccion = VALUES(Direccion),
  Departamento = VALUES(Departamento),
  Barrio = VALUES(Barrio),
  Telefono = VALUES(Telefono),
  Tipo = VALUES(Tipo),
  Promesa_de_Entrega = VALUES(Promesa_de_Entrega),
  Estado_Pedido = VALUES(Estado_Pedido),
  Asignaciones = VALUES(Asignaciones),
  Usuario_Movil = VALUES(Usuario_Movil),
  Placas_del_Usuario_Movil = VALUES(Placas_del_Usuario_Movil),
  Estado_Entrega = VALUES(Estado_Entrega),
  Fecha_Entrega = VALUES(Fecha_Entrega),
  Hora_Entrega = VALUES(Hora_Entrega),
  Nov_Entrega = VALUES(Nov_Entrega),
  Obs_Entrega = VALUES(Obs_Entrega),
  Direccion_Tercero = VALUES(Direccion_Tercero),
  Nombre_Tercero = VALUES(Nombre_Tercero),
  Foto1 = VALUES(Foto1),
  Foto2 = VALUES(Foto2),
  Foto3 = VALUES(Foto3),
  Foto4 = VALUES(Foto4),
  Foto5 = VALUES(Foto5),
  Numero_Asignacion = VALUES(Numero_Asignacion),
  Numero_Despacho = VALUES(Numero_Despacho),
  Fecha_Despacho = VALUES(Fecha_Despacho),
  Hora_Despacho = VALUES(Hora_Despacho),
  Latitud = VALUES(Latitud),
  Longitud = VALUES(Longitud),
  Pedido_Inventariado = VALUES(Pedido_Inventariado),
  Novedad_Inventario = VALUES(Novedad_Inventario),
  Observacion_Inventario = VALUES(Observacion_Inventario),
  Clasificacion_por_Valor = VALUES(Clasificacion_por_Valor),
  Subestado = VALUES(Subestado),
  Transportador = VALUES(Transportador)
