
export interface TypeIdTBPEDIDOSNOVAVENTA {
  id?: number | string;
};

export interface TypeTBPEDIDOSNOVAVENTA extends TypeIdTBPEDIDOSNOVAVENTA {
  Plataforma: string;
  Campaña: string;
  Fecha_Recepcion: string;
  Hora_Recepcion: string;
  Manifiesto: string;
  Region: string;
  Zona: string;
  Seccion: string;
  Nombre_destinatatio: string;
  Cedula: string;
  Numero_Boleta: string;
  Direccion: string;
  Departamento: string;
  Ciudad: string;
  Municipio_Enviexpres: string;
  Barrio: string;
  Telefono: string;
  Tipo: string;
  Promesa_de_Entrega: string;
  Estado_Pedido: string;
  Asignaciones: string;
  Usuario_Movil: string;
  Placas_del_Usuario_Movil: string;
  Estado_Entrega: string;
  Fecha_Entrega: string;
  Hora_Entrega: string;
  Nov_Entrega: string;
  Obs_Entrega: string;
  Direccion_Tercero: string;
  Nombre_Tercero: string;
  Foto1: string;
  Foto2: string;
  Foto3: string;
  Foto4: string;
  Foto5: string;
  Numero_Asignacion: string;
  Numero_Despacho: string;
  Fecha_Despacho: string;
  Hora_Despacho: string;
  Latitud: string;
  Longitud: string;
  Pedido_Inventariado: string;
  Novedad_Inventario: string;
  Observacion_Inventario: string;
  Clasificacion_por_Valor: string;
  Subestado: string;
  Transportador: string;
  Valor_Costo: string;
  Valor_Venta: string;
  Factura_De_Venta: string;
  Fecha_De_Venta: string;
  Pre_Liquidacion: string;
  Fecha_Pre_Liquidacion: string;
  Orden_de_Compra: string;
  Fecha_Orden_de_Compra: string;
  Leido: number;
};
